### ISSUE TITLE
Difference between custom_voc_2007_test and voc_2007_test and between your eval procedure and detectron2's one

### ISSUE THREAD

**Issue by FrancescoCappio** [Vastlab/Elephant-of-object-detection#6]
I have noticed that if I train a Faster RCNN model with the command you provided in the readme and then test it I get mAP on your custom_voc_2007_test equal to 0.7396760583. However if I use the trained model to perform eval with detectron2 on voc_2007_test I obtain 0.809274 that is much more similar to the results in Table 1 of your paper. So I think there is a difference between voc_2007_test and custom_voc_2007_test or between your eval procedure and the one used in detectron2, Can you tell me where is and what is this difference?

**Comment by akshay-raj-dhamija** [comment]
Hi!
Thank you for asking this important question.
Yes, you are right that the numbers in Table 1 of the paper are actually from detectron2 evaluation rather than the ones provided by this repo. The difference is that detectron2 uses the `PascalVOCDetectionEvaluator` which is a bit different from the one used in this repo. Here are some of the differences.

1. `PascalVOCDetectionEvaluator` ignores [difficult annotations](https://github.com/facebookresearch/detectron2/blob/bb8b293c456c43b1745b9a49725eeed3bb965dc6/detectron2/evaluation/pascal_voc_evaluation.py#L282) in PASCAL VOC
2. `PascalVOCDetectionEvaluator` uses a [11 point evaluation metric](https://github.com/facebookresearch/detectron2/blob/bb8b293c456c43b1745b9a49725eeed3bb965dc6/detectron2/evaluation/pascal_voc_evaluation.py#L162)
3. `PascalVOCDetectionEvaluator` summarizes performance on [various levels of IOU](https://github.com/facebookresearch/detectron2/blob/bb8b293c456c43b1745b9a49725eeed3bb965dc6/detectron2/evaluation/pascal_voc_evaluation.py#L101), where as we only use IOU=0.5, i.e. our AP is actually AP50. 

The reason for this mismatch is that the code used to publish the results in the paper was initially written with detectron which made the evaluation for WIC a multi-step process that would be difficult to replicate. Hence, it was rewritten with detectron2 for a more integrated and simplified code.
Apart from the evaluation differences above there were also [differences between detectron and detectron2](https://detectron2.readthedocs.io/en/latest/notes/compatibility.html?highlight=detectron#compatibility-with-detectron-and-maskrcnn-benchmark) which could add more discrepancy in the results and training.

Hope this helps and addresses your question.

**Comment by yangJirui** [comment]
Can you update the evaluation codes that **Do Not** ignore difficult annotations in Pascal Voc ? @akshay-raj-dhamija
